version: '3'

services:
  monitor:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - TZ=Asia/Shanghai
      - REDIS_HOST=redis
    extra_hosts:
    - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    networks:
      - snmp_monitor

  redis:
    image: redis
    restart: always
    container_name: redis
    networks:
      - snmp_monitor

networks:
  snmp_monitor: