version: '3'

services:
  monitor:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - TZ=Asia/Beijing
      - REDIS_HOST=host.docker.internal
      - SQL_HOST=host.docker.internal
    extra_hosts:
    - "host.docker.internal:host-gateway"